version: '3.9'

services:
  api:
    build: 
      context: .
      dockerfile: app/Dockerfile
    ports:
      - 8000:8000

  frontend:
    build: 
      context: .
      dockerfile: app_frontend/Dockerfile
    ports:
      - 8001:8001
    depends_on:
      - api
  