version: '3.9'

services:
  api:
    build: 
      context: .
      dockerfile: app/Dockerfile
    image: amt2k10/glassesdetection:api
    ports:
      - 8000:8000

  frontend:
    build: 
      context: .
      dockerfile: app_frontend/Dockerfile
    image: amt2k10/glassesdetection:frontend
    ports:
      - 8001:8001
    depends_on:
      - api

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./monitoring:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000
    depends_on:
      - prometheus
