name: api_testing_workflow

on:
  push:
    paths:
      - 'app/**'

jobs:
  api-testing:
    name: API testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          pip install httpx
          pip install dvc
          pip install dvc-gdrive
      - name: download files from DVC
        run: |
          dvc pull models/finalModelGlassDetection255.dvc
        env: 
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      - name: Test the API with pytest
        run: |
          pytest app/
