name: CI/CD

on:
  push:
    branches:
      - main
      - okteto
    paths:
      - 'app/**' 
      - 'models/finalModelGlassDetection255/**'
      - 'app_frontend/**' 
      - 'docker-compose.yml'
      - '.github/workflows/CI_CD.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-dvc@v1
      - name: Download model from DVC
        env: 
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run:
          dvc pull -v models/finalModelGlassDetection255.dvc

      - name: "Set up okteto environment"
        run: curl https://get.okteto.com -sSfL | sh
        
      - name: "Set up okteto context"
        run: okteto context use https://cloud.okteto.com --token ${{ secrets.OKTETO_GITHUB_ACTIONS }}
      
      - name: "build and push on okteto"
        run: okteto build

      - name: "deploy on okteto"
        run: okteto deploy --wait
