name: deploy

on:
  push
  # the 1st condition
  # workflow_run:
  #   workflows: ["Publish Docker image API","Publish Docker image FRONTEND"]
  #   branches: [main]
  #   types:
  #     - completed

jobs:
  deploy-packages:
    name: dvc_repro execution
    # the 2nd condition
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: "amt2k10"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: "22"
          script: whoami