name: Publish Docker image FRONTEND

on:
  push:
    branches:
      - main
    paths:
      - 'app_frontend/**' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $username -p $password
      - name: Build Docker Images
        run: docker compose build frontend
      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/glassesdetection:frontend
