name: server_check

on:
  schedule:
    - cron: '15 * * * *'


jobs:
  deployment:
    name: server check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Make Request to the server
        uses: fjogeleit/http-request-action@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: test the server
        run: |
          pytest tests/test_server.py
